import { Outfit } from "next/font/google";
import "./globals.css";
import Headers from "./_components/Headers";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="md:px-20 md:mb-20">
          <Headers />
          {children}
          <Toaster />
        </div>
        <Footer />
      </body>
    </html>
  );
}
